sudo: required

dist: xenial

language: ruby

rvm: 2.7.1

services:
  - docker

before_install:
  - curl -L https://github.com/dnephin/dobi/releases/download/v0.10/dobi-linux > dobi
  - chmod +x dobi
  - sudo mv dobi /usr/local/bin

script:
  - dobi
  - bundle exec rspec

notifications:
  webhooks: http://webhook.hakatashi.com/travis
